#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
开机自启开关 —— 在 Windows「启动」文件夹里放/删一个指向本桌宠的 vbs。

用法：
    python autostart.py on       开启开机自启
    python autostart.py off      关闭
    python autostart.py status   查看当前状态

之所以生成一个独立的 vbs（而不是直接放快捷方式），是因为创建 .lnk 要走 COM，
在某些受限环境下会被拦；vbs 复制进 Startup 文件夹即可被 Windows 执行。
"""

from __future__ import annotations

import os
import sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.join(BASE_DIR, "wb_pet.py")

# 优先用与当前解释器同目录的 pythonw，其次项目内 .venv，最后交给 PATH
LNK_NAME = "WorkBuddyWhalePet.vbs"


def startup_dir() -> str:
    return os.path.join(os.environ.get("APPDATA", ""),
                        r"Microsoft\Windows\Start Menu\Programs\Startup")


def launcher_path() -> str:
    return os.path.join(startup_dir(), LNK_NAME)


def pick_python() -> str:
    """
    挑一个用来跑桌宠的解释器：
      1) 与当前解释器同目录的 pythonw.exe（通常就是装了 PySide6 的那个）
      2) 项目内的 .venv
      3) 退回 PATH 里的 pythonw.exe
    """
    exe = sys.executable or ""
    if exe:
        d = os.path.dirname(exe)
        for name in ("pythonw.exe", "pythonw"):
            p = os.path.join(d, name)
            if os.path.exists(p):
                return p
    local = os.path.join(BASE_DIR, ".venv", "Scripts", "pythonw.exe")
    if os.path.exists(local):
        return local
    return "pythonw.exe"


def vbs_content() -> str:
    py = pick_python()
    return (
        "' WorkBuddy Whale Pet - autostart launcher (generated by autostart.py)\n"
        "Option Explicit\n"
        "Dim shell\n"
        "Set shell = CreateObject(\"WScript.Shell\")\n"
        f"shell.CurrentDirectory = \"{BASE_DIR}\"\n"
        f"shell.Run \"\"\"{py}\"\" \"\"{TARGET}\"\"\", 0, False\n"
    )


def do_on() -> int:
    d = startup_dir()
    if not os.path.isdir(d):
        print(f"[失败] 找不到启动文件夹：{d}")
        return 1
    path = launcher_path()
    try:
        with open(path, "w", encoding="utf-8") as f:
            f.write(vbs_content())
    except Exception as e:
        print(f"[失败] 写入失败：{type(e).__name__}: {e}")
        return 1
    print("[完成] 已开启开机自启")
    print(f"       启动项：{path}")
    print(f"       解释器：{pick_python()}")
    print(f"       脚本  ：{TARGET}")
    return 0


def do_off() -> int:
    path = launcher_path()
    if not os.path.exists(path):
        print("[跳过] 当前没有开启开机自启")
        return 0
    try:
        os.remove(path)
    except Exception as e:
        print(f"[失败] 删除失败：{type(e).__name__}: {e}")
        return 1
    print("[完成] 已关闭开机自启")
    print(f"       已移除：{path}")
    return 0


def do_status() -> int:
    path = launcher_path()
    on = os.path.exists(path)
    print(f"开机自启：{'已开启' if on else '未开启'}")
    print(f"启动文件夹：{startup_dir()}")
    if on:
        print(f"启动项：{path}")
    return 0


def main() -> int:
    act = (sys.argv[1] if len(sys.argv) > 1 else "status").lower()
    if act == "on":
        return do_on()
    if act == "off":
        return do_off()
    if act == "status":
        return do_status()
    print("用法：python autostart.py [on|off|status]")
    return 2


if __name__ == "__main__":
    sys.exit(main())
